let screen_w = 800.
let screen_h = 600.
let g = -9.81
let ball = Ball.create ~x:400. ~y:120. ~radius:8. ~vx:200. ~vy:200.
let paddle = Paddle.create ~x:350. ~y:80. ~width:100. ~height:15.
let max_speed = 600.
let coeff_velocity = 0.5 (* reduction de la vitesse transmise par le paddle*)
let bounce_accel = 1.02 (* acceleration appliquée à chaque rebond *)
let max_in_leaf = 4 (* maximum number of bricks inside of a quadtree leaf *)
